config/routes.rb
Rails.application.routes.draw do

  

 
  get 'main/:product_id/', to: 'categories#main', as: :main
  get 'sub_1/:id/:product_id', to: 'categories#sub_1', as: :sub_1
  get 'sub_2/:id/:product_id', to: 'categories#sub_2', as: :sub_2
  get 'sub_3/:id/:product_id', to: 'categories#sub_3', as: :sub_3
  get 'sub_4/:id/:product_id', to: 'categories#sub_4', as: :sub_4
  get 'sub_5/:id/:product_id', to: 'categories#sub_5', as: :sub_5
  get 'last/:id/:product_id',  to: 'categories#last',  as: :last
  put 'assign_ebay_category/:id/:product_id', to: 'categories#assign_ebay_category', as: :assign_ebay_category
  get 'upload_photo/:product_id/', to: 'photos#upload_photo', as: :upload_photo         

  

  resources :products do 
    member do
      get 'listing_start', to: 'products#listing_start', as: :listing_start
      get 'listing_specifics', to: 'products#listing_specifics', as: :listing_specifics
    end         
  end

  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product

	mount_uploader :image, ImageUploader

	# validates :image, presence: true

	before_save :grab_file_name

	def grab_file_name
		backword = self.image.to_s
		bw = backword.reverse
		word = ""
		i = 0
		bw.each_char do |c|
			c = bw[i]
		 	break if c == "/"
		 	word += c 
		 	i += 1
		end 
		self.name = word.reverse
	end
 
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def new
		@photo = Photo.new(:product_id => (params[:product_id]))
	end

  def upload_photo
    @photo = Photo.new(:product_id => (params[:product_id]))    
  end

  def show
    @photo = Photo.find(params[:id])
    @product = Product.find(@photo.product_id)
  end	

  def edit
    @photo = Photo.find(params[:id])
    @product = Product.find(@photo.product_id)
  end

  def create	
  	 @photo = Photo.new(photo_params)
      if @photo.save
        flash[:notice] = "Successfully created photo."
        redirect_to @photo
      else
        render :action => 'upload_photo'
      end
    end

  def update  
     @photo = Photo.find(params[:id])
     @product = Product.find(@photo.product_id)
      if @photo.save
        flash[:notice] = "Successfully created photo."
        redirect_to @photo
      else
        render :action => 'upload_photo'
      end
    end

    def destroy      
    @photo = Photo.find(params[:id])
    @product = Product.find(@photo.product_id)
    @photo.destroy
    flash[:notice] = "Successfully destroyed photo."
    redirect_to @product
  end


  private 

  def photo_params
    params.require(:photo).permit(:image, :name, :product_id, :main, :remote_image_url)
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
 <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :product_id %>

  <div class="contailer">
	  <div class="row">
		  <div class="col-md-4">
      
		  <div class="form-field fatbottom">
           <i class='small material-icons prefix'>camera_alt</i><%= f.label :image, "Upload Photo From File" %><br>
           <%= f.file_field :image, class: 'form-control' %>
      </div>	
        
		  <div class="actions">
            <%= f.submit "Submit", class: "btn btn-success"  %>
        </div>	
		  </div>
	  </div>
  </div>
 <% end %> 

app/views/photos/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div>
      <h4 style="color: gray">Photo for: <span class="item-title"><%= @product.title %></span></h4>
      <div class="upper-link">
      	<%= link_to 'Back to Product', product_path(@photo.product_id) %>
      </div>
    </div>
			<div class="photo-showpage">
      <%= image_tag @photo.image_url(:showpage) %>  
    	</div><br>   
      <%= link_to 'Show', @photo %>  	
		</div>		
	</div>
</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<div>

	<%= render 'form' %>

</div>

app/views/photos/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div>
      <h4 style="color: gray">Photo for: <span class="item-title"><%= @product.title %></span></h4>
      <div class="upper-link">
      	<%= link_to 'Back to Product', product_path(@photo.product_id) %>
      </div>
    </div>
			<div class="photo-showpage">
      <%= image_tag @photo.image_url(:showpage) %>  
    	</div>    	
		</div>		
	</div>
</div>

app/views/photos/upload_photo.html.erb
<h1>New Photo</h1>

<div>

	<%= render 'form' %>

</div>