config/routes.rb
Rails.application.routes.draw do

  

 
  get 'main/:product_id/', to: 'categories#main', as: :main
  get 'sub_1/:id/:product_id', to: 'categories#sub_1', as: :sub_1
  get 'sub_2/:id/:product_id', to: 'categories#sub_2', as: :sub_2
  get 'sub_3/:id/:product_id', to: 'categories#sub_3', as: :sub_3
  get 'sub_4/:id/:product_id', to: 'categories#sub_4', as: :sub_4
  get 'sub_5/:id/:product_id', to: 'categories#sub_5', as: :sub_5
  get 'last/:id/:product_id',  to: 'categories#last',  as: :last
  put 'assign_ebay_category/:id/:product_id', to: 'categories#assign_ebay_category', as: :assign_ebay_category
  get 'upload_photo/:product_id/', to: 'photos#upload_photo', as: :upload_photo         

  

  resources :products do 
    member do
      get 'listing_start', to: 'products#listing_start', as: :listing_start
      get 'listing_specifics', to: 'products#listing_specifics', as: :listing_specifics
    end         
  end

  resources :photos

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	

	def main 
			@product = Product.find(params[:product_id])
			@categories = EbayCategory.where('category_id = parent_id').order(:id)
	end

	def sub_1
		@product = Product.find(params[:product_id])
		@parent_category = EbayCategory.find(params[:id])
		@sub_categories = EbayCategory.where('parent_id = ?', @parent_category.category_id)
	end

	def sub_2
		@product = Product.find(params[:product_id])
		@parent_category = EbayCategory.find(params[:id])		
		@sub_categories = EbayCategory.where('parent_id = ?', @parent_category.category_id)
	end

	def sub_3
		@product = Product.find(params[:product_id])
		@parent_category = EbayCategory.find(params[:id])	
		@sub_categories = EbayCategory.where('parent_id = ?', @parent_category.category_id)
	end

	def sub_4
		@product = Product.find(params[:product_id])
		@parent_category = EbayCategory.find(params[:id])		
		@sub_categories = EbayCategory.where('parent_id = ?', @parent_category.category_id)
	end

	def sub_5
		@product = Product.find(params[:product_id])
		@parent_category = EbayCategory.find(params[:id])		
		@sub_categories = EbayCategory.where('parent_id = ?', @parent_category.category_id)
	end

	def last
		@product = Product.find(params[:product_id])
		@parent_category = EbayCategory.find(params[:id])
	end

	def assign_ebay_category
		@product = Product.find(params[:product_id])
    @category = EbayCategory.find(params[:id])
    @product.update_attributes(ebay_category: @category.category_id, workflow_state: :category_chosen)
    redirect_to listing_start_product_path(@product)
	end

	private
	 

	def category_params
      params.require(:ebay_category).permit(:category_id, :main_category, :sub_category1, :sub_category2, :sub_category3, :sub_category4, :sub_category5, :parent_id, :children, :product_id, :listing_id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

	

end

app/views/categories/last.html.erb
<div class="container">

	<div>
		<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>
	</div>

	<div class="row">
		<div class="col-md-8">	
			<h3><%= @parent_category.main_category + " > " + @parent_category.f1 +  @parent_category.f2 +  
			@parent_category.f3 + @parent_category.f4 + @parent_category.f5 %></h3>
		</div>
	</div>

	<div class="button-breathe">
		<%= form_tag assign_ebay_category_path, method: :put do %>		
   		
   		<%= submit_tag "Finalize Category Selection", class: "btn btn-success" %>
   <% end %>
	</div>

	<div class="button-breathe">
		<%= link_to "Back to Top of Categories", main_path(@product), class: "btn btn-info" %>
	</div>
   
	

</div>	

app/views/categories/main.html.erb
<div class="container">
	<div class"row">
		<div class="col-md-6" id="main_category">
			<div>
				<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>
			</div>		
				<% @categories.each do |c| %>
					<h5><%= link_to c.main_category + " >", sub_1_path(c, @product) %><h5> 
				<% end %>			
		</div>
	</div>
</div>

app/views/categories/sub_1.html.erb
<div class="container">

	<div>
		<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>
	</div>

	<div class"row">
		<div class="col-md-2">
				<h3><%= @parent_category.main_category + " > " %></h3>
		</div>
	</div>	

		<div class"row">
			<div class="col-md-3" >
				<% @sub_categories.each do |s| %>
					<% if s.children == 0 && s.sub_category1 != "" %>
						<h5><%= link_to s.sub_category1, last_path(s, @product) %></h5> 
					<% elsif s.sub_category1 != "" %>
						<h5><%= link_to s.sub_category1 + " > ", sub_2_path(s, @product)  %></h5>
					<% end %>
				<% end %>	
			</div>
		</div>

</div>

app/views/categories/sub_2.html.erb
<div class="container">

	<div>
		<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>	</div>
	<div class"row">
		<div class="col-md-2" id="main_category">
				<h3><%= @parent_category.main_category + " > " %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category1">
				<h3><%= @parent_category.sub_category1 + " > " %></h3>
		</div>
	</div>		

		<div class"row">
			<div class="col-md-3" >
				<% @sub_categories.each do |s| %>
					<% if s.children == 0 %>
						<h5><%= link_to s.sub_category2, last_path(s, @product) %></h5> 
					<% else %>
						<h5><%= link_to s.sub_category2 + " > ", sub_3_path(s, @product) %></h5>
					<% end %>
				<% end %>	
			</div>
		</div>

</div>

app/views/categories/sub_3.html.erb
<div class="container">

	<div>
		<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>
	</div>

	<div class"row">
		<div class="col-md-2" id="main_category">
				<h3><%= @parent_category.main_category + " > " %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category1">
				<h3><%= @parent_category.sub_category1 + " > " %></h3>
		</div>
	</div>	

	<div class"row">
		<div class="col-md-2" id="sub_category2">
				<h3><%= @parent_category.sub_category2 + " > " %></h3>
		</div>
	</div>

		<div class"row">
			<div class="col-md-3" >
				<% @sub_categories.each do |s| %>
					<% if s.children == 0 %>
						<h5><%= link_to s.sub_category3, last_path(s, @product) %></h5> 
					<% else %>
						<h5><%= link_to s.sub_category3 + " > ", sub_4_path(s, @product) %></h5>
					<% end %>
				<% end %>	
			</div>
		</div>

</div>

app/views/categories/sub_4.html.erb
<div class="container">

	<div>
		<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>
	</div>

	<div class"row">
		<div class="col-md-2" id="main_category">
				<h3><%= @parent_category.main_category + " > " %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category1">
				<h3><%= @parent_category.sub_category1 + " > " %></h3>
		</div>
	</div>	

	<div class"row">
		<div class="col-md-2" id="sub_category2">
				<h3><%= @parent_category.sub_category2 + " > " %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category3">
				<h3><%= @parent_category.sub_category3 + " > " %></h3>
		</div>
	</div>

		<div class"row">
			<div class="col-md-3" >
				<% @sub_categories.each do |s| %>
					<% if s.children == 0 %>
						<h5><%= link_to s.sub_category4, last_path(s, @product) %></h5> 
					<% else %>
						<h5><%= link_to s.sub_category4 + " > ", sub_5_path(s, @product) %></h5>
					<% end %>
				<% end %>	
			</div>
		</div>

</div>

app/views/categories/sub_5.html.erb
<div class="container">

	<div>
		<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Select Listing Category</h4>
	</div>

	<div class"row">
		<div class="col-md-2" id="main_category">
				<h3><%= @parent_category.main_category + ">" %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category1">
				<h3><%= @parent_category.sub_category1 + ">" %></h3>
		</div>
	</div>	

	<div class"row">
		<div class="col-md-2" id="sub_category2">
				<h3><%= @parent_category.sub_category2 + ">" %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category3">
				<h3><%= @parent_category.sub_category3 + ">" %></h3>
		</div>
	</div>

	<div class"row">
		<div class="col-md-2" id="sub_category4">
				<h3><%= @parent_category.sub_category4 + ">" %></h3>
		</div>
	</div>	

		<div class"row">
			<div class="col-md-3" >
				<% @sub_categories.each do |s| %>
					<h5><%= link_to s.sub_category5, last_path(s, @product) %></h5> 
				<% end %>	
			</div>
		</div>

</div>