config/routes.rb
Rails.application.routes.draw do

  

 
  get 'main/:product_id/', to: 'categories#main', as: :main
  get 'sub_1/:id/:product_id', to: 'categories#sub_1', as: :sub_1
  get 'sub_2/:id/:product_id', to: 'categories#sub_2', as: :sub_2
  get 'sub_3/:id/:product_id', to: 'categories#sub_3', as: :sub_3
  get 'sub_4/:id/:product_id', to: 'categories#sub_4', as: :sub_4
  get 'sub_5/:id/:product_id', to: 'categories#sub_5', as: :sub_5
  get 'last/:id/:product_id',  to: 'categories#last',  as: :last
  put 'assign_ebay_category/:id/:product_id', to: 'categories#assign_ebay_category', as: :assign_ebay_category
  get 'upload_photo/:product_id/', to: 'photos#upload_photo', as: :upload_photo         

  

  resources :products do 
    member do
      get 'listing_start', to: 'products#listing_start', as: :listing_start
      get 'listing_specifics', to: 'products#listing_specifics', as: :listing_specifics
    end         
  end

  resources :photos

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_one :package
	has_one :return_policy
	has_one :ship_detail
	has_many :photos

	include ProductsHelper
	include DetailsHelper
	include Workflow

	store_accessor :item_specifics, :clothing_color, :size_type_women, :size_women, :material_women, :pattern_women, :occasion_women, :style_women_top, :style_women_dress, :style_women_sleeve, :label_designer_women, :size_type_men, :size_men, :size_dress_shirt_men, :sleeve_length_men, :cuff_style_dress_shirt_men, :style_men_casual_shirt, :style_men_pants_jeans, :inseam_men, :bottoms_size_men, :pattern_men, :material_men, :brand_men, :sizely

	scope :unlisted, -> { where('workflow_state = ?', 'inventory_not_listed')}

	workflow do 
		state :new do 
			event :submit, :transitions_to => :inventory_not_listed			
		end		
		state :inventory_not_listed do
			event :list_item, :transitions_to => :inventory_listed
		end
		state :inventory_listed do 
			event :sell, :transitions_to =>	:sold_not_shipped		
		end
		state :sold_not_shipped do
			event :ship, :transitions_to => :sold_shipped
		end
		state :sold_shipped do
			event :accept, :transitions_to => :accepted
			event :return, :transitions_to => :returned
		end
		state :accepted
		state :returned			
	end	

  def formatted_purchase_date
    return "" if purchase_date.blank?
    purchase_date.strftime("%b %d, %Y")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  include ProductsHelper
  include DetailsHelper

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @photos = Photo.where("product_id = ?", @product.id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def assign_ebay_category
    @product = Product.find(params[:product_id])
    @category = EbayCategory.find(params[:id])
    @product.update_attributes(ebay_category: @category.category_id, item_specifics: {})
    redirect_to listing_specifics_product_path(@product)
  end

  def listing_start
    @product = Product.find(params[:id])
  end

  def listing_specifics
    @product = Product.find(params[:id])
  end

  # GET /products/1/edit
  def edit    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        @product.submit!
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/products_helper.rb
module ProductsHelper

	def store_categories
		[
			['Select Category', ''],
			['Womens Clothing', 'Womens Clothing'],
			['Mens Clothing', 'Mens Clothing'],
			['Coffee Mugs', 'Coffee Mugs'],
			['Needlepoint', 'Needlepoint'],
			['Kitchen Items', 'Kitchen Items'],
			['Office Supplies', 'Office Supplies'],
			['Other', 'Other']

		]

		# (["Women's Clothing",	"Men's Clothing", "Coffee Mugs", "Needlepoint",	"Kitchen Items", "Office Supplies",	"Other"])

	end

	

end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    		 <div class="form-field fatbottom">
	       	 <span class='small material-icons prefix'>create</span><%= f.label :title, "Item Name (short form)" %><br>
	      	 <%= f.text_field :title, class: 'form-control', placeholder: "What's this thing?" %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class='small material-icons prefix'>description</i><%= f.label :description, "Condition Description" %><br>
	        <%= f.text_area :description, class: 'form-control', style: "min-height: 130px", placeholder: "Tell us something about it..."%>
	      </div>
	      <div class="form-field fatbottom">
	        <i class='small material-icons prefix'>today</i><%= f.label :purchase_date %><br>
	        <%= f.date_field :purchase_date, class: 'form-control' %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class="small material-icons prefix">store</i><%= f.label :purchase_source %><br>
	        <%= f.text_field :purchase_source, class: 'form-control', placeholder: "Where'd you get it?" %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class='small material-icons prefix'>attach_money</i><%= f.label :purchase_price %><br>
	        <%= f.text_field :purchase_price, class: 'form-control', placeholder: "0.00"%>
	      </div>
	      <div class="form-field fatbottom">
	         <i class='small material-icons prefix'>folder_open</i>
	         <%= f.label :store_category, 'Store Category' %><br>           
	         <%= f.select(:store_category, options_for_select(store_categories, @product.store_category), {}, {class: 'form-control', placeholder: "Select a Category"}) %>          
	      </div><br>
	      <div class="actions">
	          <%= f.submit "Create Product", class: "btn btn-success"  %>
	      </div><br><br>	    
<% end %>

<script type="text/javascript">
  // $('select').selectpicker();

</script>

app/views/products/_mens_clothing_details.html.erb
			<%= form_for(@product) do |f| %>
				  	<% if @product.errors.any? %>
					    <div id="error_explanation">
					      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
					      <ul>
						      <% @product.errors.full_messages.each do |message| %>
						        <li><%= message %></li>
						      <% end %>
					      </ul>
					    </div>
				  	<% end %>

	<div class="container">
		<div class"row">
			<div class="col-md-4" >			
				<div class="fatbottom">
					<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Listing Specifics</h4> 
					<h4 style="color: gray">Store Category: <b style="color: #444041"><%= @product.store_category %></b></h4>  				
				</div>
				<div class="form-field fatbottom">
				 <i class='flaticon-paint81'></i><%= f.label :clothing_color, "Garment Color" %><button  class="btn btn-default btn-xs flipper">Enter your Own</button><br>
				 		<%= f.text_field :clothing_color, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new color'} %>	     	 										
	      	  <%= f.select(:clothing_color, options_for_select(clothing_color), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>					      	 
        </div>      	  
    		<div class="form-field fatbottom">
	       	 <i class='flaticon-tie13'></i><%= f.label :size_type_men, "Size Category" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	       	 <%= f.text_field :size_type_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new size category'} %>
	      	 <%= f.select(:size_type_men, options_for_select(size_type_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class='flaticon-measure'></i><%= f.label :size_men, "Size" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br>
	        <%= f.text_field :size_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new size'} %>
	        <%= f.select(:size_men, options_for_select(size_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div>		            
	      <div class="form-field fatbottom">
	        <i class="flaticon-clothing46"></i><%= f.label :size_dress_shirt_men, "Size (Dress Shirt)" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        <%= f.text_field :size_dress_shirt_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new dress shirt size'} %>
	        <%= f.select(:size_dress_shirt_men, options_for_select(size_dress_shirt_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div>
	       <div class="form-field fatbottom" >
	        	<i class="flaticon-clothing53"></i><%= f.label :sleeve_length_men, "Sleeve Length" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        	<%= f.text_field :sleeve_length_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new sleeve length'} %>
	          <%= f.select(:sleeve_length_men, options_for_select(sleeve_length_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div>
	      <div class="form-field fatbottom" >
	        	<i class="fa fa-thumbs-o-up fa-2x fa-fw"></i><%= f.label :cuff_style_dress_shirt_men, "Cuff Style" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        	<%= f.text_field :cuff_style_dress_shirt_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new cuff style'} %>
	          <%= f.select(:cuff_style_dress_shirt_men, options_for_select(cuff_style_dress_shirt_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div> 
	      <div class="form-field fatbottom" >
	        	<i class="flaticon-clothing71"></i><%= f.label :style_men_casual_shirt, "Style (Casual Shirt)" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        	<%= f.text_field :style_men_casual_shirt, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new top style'} %>
	          <%= f.select(:style_men_casual_shirt, options_for_select(style_men_casual_shirt), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div> 
	     
	    </div>
	  </div>  
    <!-- <div class="row"> -->
    	<div class="col-md-4">
				<div class="form-field fatbottom" style="margin-top: 76px;">
	        	<i class="flaticon-clothing173"></i><%= f.label :style_men_pants_jeans, "Style (Mens Pants/Jeans)" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        	<%= f.text_field :style_men_pants_jeans, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new dress/skirt style'} %>
	          <%= f.select(:style_men_pants_jeans, options_for_select(style_men_pants_jeans), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>	      
	      </div>
	      <div class="form-field fatbottom" >
	        	<i class="flaticon-clothing166"></i><%= f.label :inseam_men, "Inseam" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        	<%= f.text_field :inseam_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new inseam measurement'} %>
	          <%= f.select(:inseam_men, options_for_select(inseam_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>	      
	      </div>
	      <div class="form-field fatbottom" >
	        	<i class="flaticon-baby62"></i><%= f.label :bottoms_size_men, "Bottoms Size (men)" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        	<%= f.text_field :bottoms_size_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new bottoms size'} %>
	          <%= f.select(:bottoms_size_men, options_for_select(bottoms_size_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>	      
	      </div>    	
	      <div class="form-field fatbottom" >
	        <i class="flaticon-circle72"></i><%= f.label :pattern_men, "Pattern" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br>
	        <%= f.text_field :pattern_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new pattern'} %>
	        <%= f.select(:pattern_men, options_for_select(pattern_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>
	      </div> 
	       <div class="form-field fatbottom">
	        <i class='flaticon-fabric'></i><%= f.label :material_men, "Material/Fabric" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br>
	        <%= f.text_field :material_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new material'} %>
	        <%= f.select(:material_men, options_for_select(material_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false})  %>
	      </div>		     
	      <div class="form-field fatbottom" style="padding-top: 10px;">
	        <i class='fa fa-tags fa-2x fa-fw'></i><%= f.label :brand_men, "Label/Designer" %><button class="btn btn-default btn-xs flipper">Enter your Own</button><br><br>
	        <%= f.text_field :brand_men, {class: 'form-control', style: 'display: none', disabled: true, placeholder: 'Add a new label/designer'} %>
	        <%= f.select(:brand_men, options_for_select(brand_men), {:include_blank => 'Select'}, {class: 'form-control', disabled: false}) %>	        
	      </div>
	      <div class="form-field fatbottom" style="padding-top: 10px;">
	        <i class="fa fa-arrow-down fa-2x fa-fw"></i><%= f.label :sizely, "SIZE.LY IMAGE (SEE BELOW!)" %><br>
	        <%= f.text_field :sizely, {class: 'form-control', placeholder: 'Paste Size.ly Html Code Here'} %>                
	      </div><br>	     
	      <div class="actions">
	          <%= f.submit "Continue", class: "btn btn-info" %>
	      </div>	     
	    </div>
	  <!-- </div> -->
	</div>
	    <% end %> 
	<div class="container">
	    <i class="fa fa-arrow-down fa-3x"></i>
	    <h2><b>Size.ly</b><h2><h4> is a wonderful, FREE service allowing you to graphically enter detailed garment measurements.</h4>
	    <p><b>Instructions:</b></p>
	    <ol>
	    	<li>Click <span class="fa fa-arrow-down"></span>Toggle Size.ly Window for Measurements"</li>
	    	<li>Select garment type</li>
	    	<li>Enter measurements (in inches or centimeters)</li>
	    	<li>Click "Generate Image"</li>
	    	<li>Copy HTML CODE</li>
	    	<li>Click "Toggle Size.ly Window" to close</li>
	    	<li>Paste Code into "Size.ly Image"</li>
	    </ol>
	    <button class="btn btn-primary" id="sizely">Toggle Size.ly Window for Measurements</button>
	    <div  id="sizely-window" style="display: none;">
	    	<iframe src="http://size.ly/#tops" id="sizely-frame"></iframe>
	    </div>
	</div><br><br><br>
	      

  <div>Icon made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>
	</div>



	     <script type="text/javascript">	     

	     $.fn.toggleDisabled = function () {
        return this.each(function () {
            var $this = $(this);
            if ($this.prop('disabled')) {
                $this.prop('disabled', false).fadeIn('slow');
            } else {
                $this.prop('disabled', true).hide();
            }
        });
    	};

    	 $.fn.toggleLabel = function () {
        return this.each(function () {
            var $this = $(this);
            console.log($this.text());
            if ($this.text() === 'Enter your Own') {
                $this.text('Select from DropDown');
            } else {
                $this.text('Enter your Own');
            }
        });
    	};	    

			  $('.flipper').click(function(e){
			  	e.preventDefault();			  
			  	$(this).nextAll().toggleDisabled();
			  	$(this).toggleLabel();
			  }); 

			  $('#sizely').click(function(e) {
			  	e.preventDefault();
	     	$('#sizely-window').slideToggle();
	     	$('.form-field').slideToggle();
	     	$('.actions').toggle()
	     });

	     </script>  

app/views/products/edit.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-6 col-md-offset-3">
			<h1>Editing Product</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @product %> |
			<%= link_to 'Back', products_path %>
		</div>
	</div>
</div>

app/views/products/index.html.erb
<div class="container">

    <p id="notice"><%= notice %></p>

    <h1>Inventory</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Item Name</th>          
          <th>Purchase Date</th>
          <th>Purchase Source</th>
          <th>Purchase Price</th>
          <th>Store Category</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td id="title"><%= product.title %></td>            
            <td><%= product.formatted_purchase_date %></td>
            <td><%= product.purchase_source %></td>
            <td><%= number_to_currency(product.purchase_price) %></td>
            <td><%= product.store_category %></td>
            <td><%= link_to 'Show |', product  %></td>
            <td><%= link_to 'Edit |', edit_product_path(product) %></td>
            <td><%= link_to 'List Now', main_path(product), class: "btn btn-primary btn-sm" %></td>
            <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <%= link_to 'New Product', new_product_path %>
  
</div>

app/views/products/listing_specifics.html.erb
<div>
			
		<%= render current_product_store_category %>
		 
</div>

app/views/products/listing_start.html.erb
<div class="container">
	<div class"row">
		<div class="col-md-5 col-md-offset-3" >
		<%= form_for(@product) do |f| %>
		  	<% if @product.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
			      <ul>
				      <% @product.errors.full_messages.each do |message| %>
				        <li><%= message %></li>
				      <% end %>
			      </ul>
			    </div>
		  	<% end %>

				<div class="fatbottom">
					<h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span> -- Create Listing</h4> 
					<h4 style="color: gray">Store Category: <b style="color: #444041"><%= @product.store_category %></b></h4> 					
				</div>
				<div class="form-field fatbottom">
       	 <i class='fa fa-pencil fa-2x fa-fw'></i><%= f.label :listing_title, "Full Listing Title" %><br>
      	 <%= f.text_field :listing_title, class: 'form-control', placeholder: "Enter Title for eBay Listing" %>
      	</div>  
    		<div class="form-field fatbottom">
	       	 <i class='fa fa-barcode fa-2x fa-fw'></i><%= f.label :upc %><br>
	      	 <%= f.text_field :upc, class: 'form-control', placeholder: "Enter 12-digit Universal Product Code (if available)" %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class='material-icons prefix' style="font-size: 30px">redeem</i><%= f.label :condition %><br>
	        <%= f.select(:condition, options_for_select(item_condition), {:include_blank => 'Select'}, {class: 'form-control' }) %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class='material-icons prefix' style="font-size: 30px">playlist_add</i><%= f.label :quantity %><br>
	        <%= f.text_field :quantity, class: 'form-control', value: 1 %>
	      </div>
	      <div class="form-field fatbottom" id="format">
	        <i class="fa fa-bullhorn fa-2x fa-fw"></i><%= f.label :listing_format %><br>
	        <%= f.select(:listing_format, options_for_select(format_type), {:include_blank => 'Select'}, {class: 'form-control', id: 'format-field'}) %>
	      </div>
	       <div class="form-field fatbottom duration" id="auction">
	        	<i class="fa fa-hourglass-1 fa-2x fa-fw"></i><%= f.label :listing_duration, "Listing Duration" %><br>
	          <%= f.select(:listing_duration, options_for_select(durations), {}, {class: 'form-control', id: 'format-choices'}) %>
	      </div>	     
	      <div class="form-field fatbottom">
	        <i class='fa fa-usd fa-2x fa-fw'></i><%= f.label :listing_price %><br>
	        <%= f.text_field :listing_price, class: 'form-control', placeholder: "0.00"%>
	      </div>
	      <div class="form-field fatbottom">
	         <i class='material-icons prefix' style="font-size: 30px">gps_fixed</i>
	         <%= f.label :item_location, 'Item Location' %><br>           
	         <%= f.text_field :item_location,  class: 'form-control', value: "Las Vegas, NV, 89102, United States" %>
	      </div>
	      <div class="form-field fatbottom">
	        <i class="fa fa-flag fa-2x fa-fw"></i><%= f.label :country_region_of_manufacture, "Country/Region of Manufacture" %><br>
	        <%= f.select(:country_region_of_manufacture, options_for_select(countries), {}, {class: 'form-control'}) %>
	      </div>
	      <br>
	      <div class="actions">
	          <%= f.submit "Continue", class: "btn btn-info"  %>
	      </div><br><br>	    
		<% end %>
						
		</div>
	</div>
</div>

<script type="text/javascript">
		var listFormat = $('#format-field').val();
		$('#format-choices').children().eq(0).attr("disabled", true);

		function setList(lFormat) {
		if (lFormat === "Auction") {
			console.log($('#format-choices').children().eq(0).text());
			$('#format-choices').children().eq(1).show();
			$('#format-choices').children().eq(6).hide();
			$('#format-choices').children().eq(7).hide();		
		} else if (lFormat === "Fixed Price") {
			console.log($('#format-choices').children().eq(6).text());
			$('#format-choices').children().eq(1).hide();
			$('#format-choices').children().eq(6).show();
			$('#format-choices').children().eq(7).show();	
			}
		}

	$('#format-field').change(function() {
		listFormat = $(this).val();
		setList(listFormat);
		});

		

</script>
 

app/views/products/new.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-5 col-md-offset-3">

			<h2>New Product</h2>

				<%= render 'form' %>

			<%= link_to 'Back', products_path %>

		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
    <div>
      <h4 style="color: gray">Item: <span class="item-title"><%= @product.title %></span></h4>
      <h4 style="color: gray">Store Category: <b style="color: #444041"><%= @product.store_category %></b></h4> 
    </div>

 <div class="row">
    <ul>
    <% @photos.each do |photo| %>      
         <li class="photo"><%= image_tag photo.image_url(:thumb) if photo.image? %><br>
         <%= link_to photo.name, photo_path(photo) %> | <%= link_to "delete", photo, :confirm => 'Are you sure?', :method => :delete %></li>     
     <% end %>
    </ul>
  </div> 

     
   <div class="btn-group link-row" role="group" aria-label="...">
      <%= link_to 'Edit Product', edit_product_path(@product), {class: "btn btn-default"} %> 
      <%= link_to 'Back', products_path, {class: "btn btn-default"} %> 
      <%= link_to 'Add Photo', upload_photo_path(@product), {class: "btn btn-default"} %>
   </div><br><br>

  <div class="row">
    <div class="col-md-3">      

      <p>
        <strong>Description:</strong><br> 
        <%= @product.description %>
      </p>
      

      <p>
        <strong>Purchase date:</strong>
        <%= @product.formatted_purchase_date %>
      </p>

      <p>
        <strong>Purchase source:</strong>
        <%= @product.purchase_source %>
      </p>

      <p>
        <strong>Purchase price:</strong>
        <%= number_to_currency(@product.purchase_price) %>
      </p>

      <p>
        <strong>Store Category:</strong>
        <%= @product.store_category %>
      </p>

      <p>
        <strong>eBay Category:</strong>
        <%= @product.ebay_category %>
      </p>

      <p>
        <strong>UPC:</strong>
        <%= @product.upc %>
      </p>

      <p>
        <strong>Listing Title:</strong>
        <%= @product.listing_title %>
      </p>

      <p>
        <strong>Listing Price:</strong>
        <%= number_to_currency(@product.listing_price) %>
      </p>
    </div>
 
    <div class="col-md-3">

      <p>
        <strong>Listing Format:</strong>
        <%= @product.listing_format %>
      </p>

      <p>
        <strong>Listing Duration:</strong>
        <%= @product.listing_duration %>
      </p>

      <p>
        <strong>Condition:</strong>
        <%= @product.condition %>
      </p>

      <p>
        <strong>Quantity:</strong>
        <%= @product.quantity %>
      </p>

      <p>
        <strong>Item Location:</strong>
        <%= @product.item_location %>
      </p>

      <p>
        <strong>Country/Region of Manufacture:</strong>
        <%= @product.country_region_of_manufacture %>
      </p>
      <p>
        <strong>Item Location:</strong>
        <%= @product.item_location %>
      </p><br>
      
    </div>

    <div class="col-md-3">
      <dl>
        <% if @product.item_specifics %>    
          <% @product.item_specifics.each do |key, value|  %>
            <dt><%= key.humanize if !value.blank? && key != 'sizely' %></dt>
            <dd><%= value if key != 'sizely' %></dd>
          <% end %>
        <% end %> 
      </dl>
    </div> 

    <div class="col-md-3">      
      <%= link_to_if(@product.ebay_category.blank?, 'Choose Category', main_path(@product), {class: 'btn btn-primary'}) %>
      <%= link_to 'Edit Category Choice', main_path(@product) %><br><br>
      <%= link_to_if(@product.listing_title.blank?, 'Continue Listing', listing_start_product_path(@product), {class: 'btn btn-info'}) %>
      <%= link_to 'Edit Primary Listing Data', listing_start_product_path(@product) %><br><br>
      <%= link_to_if(@product.item_specifics.blank?, 'Add Item Specifics', listing_specifics_product_path(@product), {class: 'btn btn-warning'}) %>
      <%= link_to 'Edit Item Specifics', listing_specifics_product_path(@product) %></div>    
    </div><br>
    <div>
      <% if @product.item_specifics %>
          <% if @product.item_specifics['sizely'] %>
            <h2><b>Sizely </b>Measurements<h2>
            <%= content_tag(@product.item_specifics['sizely'])  %>
          <% end %>
      <% end %>
    </div>


</div> 